# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

a = int(input())

if a % 2 == 0 and a<0:
  print("отрицательное четное число");
elif a == 0:
  print ("нулевое число");
elif a % 2 ==  0 and a>0:
  print ("положительное четное число")
else:
  print ("число не является четным")