# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

x = input()
a = 0
e = 0
i = 0 
u = 0
o = 0

aa="a"
ee="e"
ii="i"
uu="u"
oo="o"

if aa in x and ee in x and ii in x and uu in x and oo in x:
  for g in x:
    if "a" in g:
      a+=1
    elif "e" in g:
      e+=1
    elif "i" in g:
      i+=1
    elif "u" in g:
      u+=1
    elif "o" in g:
      o+=1
  print("a=",a, "e=",e, "i=",i, "u=",u, "o=",o)
else:
  print("false")