# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

x = int(input("Введите минимальную сумму инвестиции "))
a = int(input("Введите сколько может инвестировать Майк "))
b = int(input("Введите сколько может инвестировать Иван "))

if a + b >= x and a < x and b < x:
  print(1)
elif a>x and b>x:
  print(2);
elif a>=x and b<x:
  print("Mike");
elif a<x and b>=x:
  print("Ivan")
else:
  print(0)